### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by armando-fandango** [jeremyadamsfisher/icd-codex#42]
* icdcodex version:
* Python version:
* Operating System:

### Description

Please make available a conda package.

**Comment by jeremyadamsfisher** [comment]
I'd be happy to do so if there is a particular reason, but since this package is pure python (and doesn't interface with compiled binaries) I just don't see there being an advantage. Could you elaborate on your use-case?

You can specify always just specify a Pip package in a conda environment:

```
name: test-env
dependencies:
- python>=3.6
- pip
- pip:
  - icdcodex==0.4.5 
 ```
