### ISSUE TITLE
Please add support for ICD-10 2023 version.

### ISSUE THREAD

**Issue by VeronikaArefeva** [jeremyadamsfisher/icd-codex#45]
Hi,

we noticed when using the library that there is missing support for 2023 updates. Therefore we can't encode some codes, e.g. G90.A

**Comment by jeremyadamsfisher** [comment]
I’ll try to get to this when I return to the US (March 27th).In the meantime, PRs are welcome.On Mar 17, 2023, at 5:49 AM, Veronika Arefeva ***@***.***> wrote:﻿
Hi,
we noticed when using the library that there is missing support for 2023 updates. Therefore we can't encode some codes, e.g. G90.A

**Comment by jeremyadamsfisher** [comment]
Added in 0.4.8

**Comment by VeronikaArefeva** [comment]
Hi Jeremy,Thanks a lot for updating the library! I had one question about reproducibility of vectors depending on different versions of sub-dependencies of icdcodex. For example, gensim, node2vec, and numpy are one of those - changing their versions either causes installation issues or yields different vectors for the same icd code even if I set the seed of say 123 when creating the Icd2Vec model.Would you recommend any specific set of versions of sub-dependencies for reproducibility that tend to work best, or any other experience you could share on your side? Thank you in advance!Thanks,Veronika03.05.2023, в 08:24, Jeremy Fisher ***@***.***>:﻿
Closed #45 as completed.
