### ISSUE TITLE
[request] Remove 'sklearn' from requirements

### ISSUE THREAD

**Issue by fitzgeraldja** [jeremyadamsfisher/icd-codex#46]
Hi there,

This package has generally been very helpful, thanks! I've noticed though that in your requirements you use 'sklearn' instead of 'scikit-learn' - this is deprecated, please change when possible - can cause issues w other packages on some machines!

Thanks,
John

**Comment by jeremyadamsfisher** [comment]
I'm glad you find the library useful. Thanks for the tip! I've addressed this in version 0.4.7.
