### ISSUE TITLE
AssertionError due to exhaustive year list

### ISSUE THREAD

**Issue by ajaykumarbharaj** [jeremyadamsfisher/icd-codex#47]
* icdcodex version: 0.4.8
* Python version: 3.9
* Operating System: Linux

### Description

```
embedder.fit(*hierarchy.icd10cm()) 
```
throwing assertion error.  hierarchy.py has a exhaustive list till year 2023. failing for year 2024 (Happy New year !)

**Comment by jeremyadamsfisher** [comment]
Happy New Year 🥳

Looks like I need to add the latest icd codes.

In the mean time, just specify the 2023 version: `embedder.fit(*hierarchy.icd10cm(version="2023"))`

**Comment by jeremyadamsfisher** [comment]
Fixed with the latest release

**Comment by Mufassir-Chowdhury** [comment]
Happy New Year! This broke again, can you use warnings for outdated lists and use the latest list available instead while you add the new list?

**Comment by jeremyadamsfisher** [comment]
Happy new year!

I added the latest codes with 0.5.2, along with a few bug fixes.

This should fix your issue for now.  To make sure your code does not break, please use a specific year like so:

```
from icdcodex import hierarchy

icd_10_cm_hierarchy, icd_10_cm_codes = hierarchy.icd10cm("2025")
```
